"use strict";
var MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
var MONTHS_KEY={janeiro:0,fevereiro:1,marco:2,abril:3,maio:4,junho:5,julho:6,agosto:7,setembro:8,outubro:9,novembro:10,dezembro:11};
var CAT_ORDER=["Entrega","Assinatura","Emissão de O.S.","Visita","Institucional","Outros"];
var COLORS={"Entrega":"#F5B400","Assinatura":"#0B5CC7","Emissão de O.S.":"#7A1FA2","Visita":"#DF1717","Institucional":"#0C9A43","Outros":"#90959D"};
function norm(v){return (v==null?"":String(v)).normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();}
function esc(v){return String(v==null?"":v).replace(/[&<>\"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c];});}
function intVal(v){var n=parseInt(String(v==null?"":v).replace(/[^0-9-]/g,""),10);return isFinite(n)?n:null;}
function parseDate(v){if(!v)return null;if(Object.prototype.toString.call(v)==="[object Date]"&&!isNaN(v.getTime()))return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==="number"){var d0=new Date(v);if(!isNaN(d0.getTime()))return new Date(d0.getFullYear(),d0.getMonth(),d0.getDate());}var s=String(v).trim();var m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);var br=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(br)return new Date(+br[3],+br[2]-1,+br[1]);var d=new Date(s);if(!isNaN(d.getTime()))return new Date(d.getFullYear(),d.getMonth(),d.getDate());return null;}
function fmtDate(d){if(!d)return "";return String(d.getDate()).padStart(2,"0")+"/"+String(d.getMonth()+1).padStart(2,"0")+"/"+d.getFullYear();}
function sameDate(a,b){return !!(a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate());}
function keyDate(d){return d?d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"):"";}
function qMonth(text){var s=norm(text);for(var k in MONTHS_KEY){if(s.indexOf(k)>=0)return MONTHS_KEY[k];}return null;}
function deriveCategory(cat,tip){if(cat&&CAT_ORDER.indexOf(String(cat).trim())>=0)return String(cat).trim();var s=norm(cat||tip);if(s.indexOf("entrega")>=0)return "Entrega";if(s.indexOf("assinatura")>=0)return "Assinatura";if(s.indexOf("ordem")>=0||s.indexOf("o.s")>=0)return "Emissão de O.S.";if(s.indexOf("visita")>=0)return "Visita";if(s.indexOf("lancamento")>=0||s.indexOf("coletiva")>=0||s.indexOf("institucional")>=0)return "Institucional";return "Outros";}
function deriveType(type,date,q){var s=norm(type);if(s.indexOf("exata")>=0||s.indexOf("especific")>=0)return "Data Exata";if(s.indexOf("quinz")>=0)return "Quinzena";if(s.indexOf("sem data")>=0)return "Sem Data";if(date)return "Data Exata";if(q)return "Quinzena";return "Sem Data";}
function monthRange(from,to){var out=[];var a=new Date(from.getFullYear(),from.getMonth(),1), b=new Date(to.getFullYear(),to.getMonth(),1);while(a<=b){out.push({y:a.getFullYear(),m:a.getMonth()});a=new Date(a.getFullYear(),a.getMonth()+1,1);}return out;}
function readBool(objects,objectName,propertyName,defaultValue){try{var o=objects&&objects[objectName];var v=o&&o[propertyName];return typeof v==="boolean"?v:defaultValue;}catch(e){return defaultValue;}}
function Visual(options){this.host=options.host;this.target=options.element;this.selectionManager=this.host&&this.host.createSelectionManager?this.host.createSelectionManager():null;this.events=[];this.settings={showTopBar:true,showFooter:true};this.state={month:(new Date()).getMonth(),year:(new Date()).getFullYear(),day:null,category:null,forecast:null};this.root=document.createElement("div");this.root.className="mcid-calendar-root";this.target.appendChild(this.root);this.tooltip=document.createElement("div");this.tooltip.className="mcid-tooltip";this.root.appendChild(this.tooltip);this.toast=document.createElement("div");this.toast.className="mcid-toast";this.toast.textContent="Evento selecionado para navegação";this.root.appendChild(this.toast);this._initialized=false;this.showLanding();}
Visual.prototype.showLanding=function(){this.root.innerHTML='<div class="mcid-landing"><div class="mcid-landing-box"><h2>Calendário Executivo MCid</h2><p>O visual foi importado corretamente. Para ativá-lo, associe os campos da tabela <b>Base</b> aos campos do visual.</p><div class="mcid-map-table"><div><b>Id Evento</b> → Id Evento</div><div><b>Data Específica</b> → Data Específica (se houver)</div><div><b>Data Quinzena</b> → Data Quinzena</div><div><b>Ano do Evento</b> → Ano do Evento</div><div><b>Tipo Data</b> → Tipo Data</div><div><b>Quinzena Nº</b> → Quinzena Nº</div><div><b>Categoria Calendário</b> → Categoria Calendário</div><div><b>Tipologia</b> → Tipologia do Evento</div><div><b>Empreendimento</b> → Nome do Empreendimento / Medida / Ação</div><div><b>Município</b> → Município</div><div><b>UF</b> → Sigla Estado</div><div><b>Secretaria</b> → Unidade responsável</div></div><div class="mcid-warn">O visual não cria datas artificiais: Data Específica vai ao dia exato; Data Quinzena fica nas previsões por quinzena; registros sem ambas permanecem em Sem Data.</div></div></div>';};
Visual.prototype.update=function(options){var dv=options&&options.dataViews&&options.dataViews[0];if(dv&&dv.metadata){var objs=dv.metadata.objects;this.settings.showTopBar=readBool(objs,"appearance","showTopBar",true);this.settings.showFooter=readBool(objs,"appearance","showFooter",true);}if(!dv||!dv.table||!dv.table.rows||!dv.table.columns||dv.table.columns.length===0){this.showLanding();return;}this.dataView=dv;var table=dv.table;var ri={};table.columns.forEach(function(c,i){var roles=c&&c.roles||{};Object.keys(roles).forEach(function(r){if(roles[r])ri[r]=i;});});var need=["idEvento","dataEspecifica","dataQuinzena","anoEvento","tipoData","quinzenaN","categoriaCalendario","tipologia","empreendimento","municipio","uf","secretaria"];var self=this;this.events=table.rows.map(function(row,rowIndex){function v(role){var i=ri[role];return i===undefined?null:row[i];}var date=parseDate(v("dataEspecifica"));var q=String(v("dataQuinzena")||"").trim();var type=deriveType(v("tipoData"),date,q);var year=intVal(v("anoEvento"));if(!year&&date)year=date.getFullYear();var qn=intVal(v("quinzenaN"));if(!qn&&q)qn=norm(q).indexOf("2")===0?2:1;var qm=qMonth(q);var cat=deriveCategory(v("categoriaCalendario"),v("tipologia"));var sid=null;try{sid=self.host.createSelectionIdBuilder().withTable(table,rowIndex).createSelectionId();}catch(e){}return{rowIndex:rowIndex,id:v("idEvento"),date:date,q:q,year:year,qm:qm,qn:qn,type:type,cat:cat,tip:String(v("tipologia")||"Sem tipologia"),project:String(v("empreendimento")||"–"),city:String(v("municipio")||"–"),uf:String(v("uf")||"–"),secretaria:String(v("secretaria")||"–"),selectionId:sid};});
  var dates=this.events.filter(function(e){return e.date;}).map(function(e){return e.date;});var years=this.events.map(function(e){return e.year;}).filter(Boolean);var today=new Date();var minD=dates.length?new Date(Math.min.apply(null,dates)):new Date(Math.min.apply(null,years.length?years:[today.getFullYear()]),0,1);var maxD=dates.length?new Date(Math.max.apply(null,dates)):new Date(Math.max.apply(null,years.length?years:[today.getFullYear()]),11,31);if(years.length){minD=new Date(Math.min(minD.getFullYear(),Math.min.apply(null,years)),0,1);maxD=new Date(Math.max(maxD.getFullYear(),Math.max.apply(null,years)),11,31);}this.monthOptions=monthRange(minD,maxD);var exists=this.monthOptions.some(function(x){return x.y===self.state.year&&x.m===self.state.month;});if(!exists){this.state.year=today.getFullYear();this.state.month=today.getMonth();}this.render();};
Visual.prototype.render=function(){var self=this;this.root.classList.toggle('mcid-no-topbar',!this.settings.showTopBar);this.root.innerHTML='';this.tooltip=document.createElement("div");this.tooltip.className="mcid-tooltip";this.root.appendChild(this.tooltip);this.toast=document.createElement("div");this.toast.className="mcid-toast";this.toast.textContent="Evento selecionado para navegação";this.root.appendChild(this.toast);
  if(this.settings.showTopBar){var top=document.createElement("div");top.className="mcid-topbar";top.innerHTML='<div class="mcid-brand"><span class="mcid-appgrid">'+('<i></i>'.repeat(9))+'</span><span>MINISTÉRIO DAS CIDADES</span><span class="mcid-brand-sep"></span><span class="mcid-brand-sub">Dashboard Executivo</span></div><div class="mcid-top-meta">Calendário institucional • sem horários</div>';this.root.appendChild(top);}else{this.root.classList.add("mcid-no-topbar");}
  var shell=document.createElement("div");shell.className="mcid-shell";this.root.appendChild(shell);
  var title=document.createElement("div");title.className="mcid-titlebar";title.innerHTML='<div class="mcid-titlewrap"><div class="mcid-title-icon"></div><div><div class="mcid-title">Calendário de Eventos</div><div class="mcid-subtitle">Visão mensal dos eventos institucionais.</div></div></div><div class="mcid-nav"><button class="mcid-btn prev" aria-label="Mês anterior">‹</button><select class="mcid-month-select" aria-label="Selecionar mês"></select><button class="mcid-btn next" aria-label="Mês seguinte">›</button><button class="mcid-btn today">Hoje</button></div>';shell.appendChild(title);
  var select=title.querySelector('.mcid-month-select');(this.monthOptions||[]).forEach(function(x){var o=document.createElement('option');o.value=x.y+'-'+x.m;o.textContent=MONTHS[x.m]+' de '+x.y;if(x.y===self.state.year&&x.m===self.state.month)o.selected=true;select.appendChild(o);});select.addEventListener('change',function(){var p=this.value.split('-');self.state.year=+p[0];self.state.month=+p[1];self.state.day=null;self.state.forecast=null;self.render();});title.querySelector('.prev').onclick=function(){self.shiftMonth(-1);};title.querySelector('.next').onclick=function(){self.shiftMonth(1);};title.querySelector('.today').onclick=function(){var d=new Date();self.state.month=d.getMonth();self.state.year=d.getFullYear();self.state.day=null;self.state.category=null;self.state.forecast=null;self.render();};
  var grid=document.createElement('div');grid.className='mcid-grid';shell.appendChild(grid);
  grid.appendChild(this.renderForecast());grid.appendChild(this.renderLegend());grid.appendChild(this.renderCalendar());grid.appendChild(this.renderEvents());
  if(this.settings.showFooter){var footer=document.createElement('div');footer.className='mcid-footer';footer.innerHTML='<span>MINISTÉRIO DAS CIDADES • dados do modelo Power BI</span><span>Calendário MCid v1.0.2</span>';shell.appendChild(footer);}
};
Visual.prototype.shiftMonth=function(delta){var d=new Date(this.state.year,this.state.month+delta,1);this.state.year=d.getFullYear();this.state.month=d.getMonth();this.state.day=null;this.state.forecast=null;this.render();};
Visual.prototype.forecastEvents=function(kind){var y=this.state.year,m=this.state.month;return this.events.filter(function(e){if(kind==='nodate')return e.type==='Sem Data';if(e.type!=='Quinzena')return false;return e.year===y&&e.qm===m&&e.qn===(kind==='q1'?1:2);});};
Visual.prototype.renderForecast=function(){var self=this;var box=document.createElement('div');box.className='mcid-card mcid-forecast';box.innerHTML='<div class="mcid-section-head"><div class="mcid-section-title">PREVISÕES SEM DATA DEFINIDA</div><div class="mcid-info">Eventos sem data específica aparecem por quinzena e não são posicionados em um dia exato.</div></div>';var cards=document.createElement('div');cards.className='mcid-forecast-cards';[['q1','1ª Quinzena','▦',''],['q2','2ª Quinzena','▦','q2'],['nodate','Sem Data','—','nodate']].forEach(function(x){var n=self.forecastEvents(x[0]).length;var b=document.createElement('button');b.className='mcid-forecast-btn '+x[3]+(self.state.forecast===x[0]?' active':'');b.innerHTML='<span class="mcid-ficon">'+x[2]+'</span><span><div class="mcid-fname">'+x[1]+'</div><div class="mcid-fcount">'+n+' '+(n===1?'evento':'eventos')+'</div></span>';b.onclick=function(){self.state.forecast=self.state.forecast===x[0]?null:x[0];self.state.day=null;self.state.category=null;self.render();};cards.appendChild(b);});box.appendChild(cards);return box;};
Visual.prototype.renderLegend=function(){var self=this;var box=document.createElement('div');box.className='mcid-card mcid-legend';box.innerHTML='<div class="mcid-section-title">LEGENDA</div>';var list=document.createElement('div');list.className='mcid-legend-list';CAT_ORDER.forEach(function(c){var it=document.createElement('div');it.className='mcid-legend-item'+(self.state.category===c&&!self.state.day?' active':'');it.innerHTML='<span class="mcid-swatch" style="background:'+COLORS[c]+'"></span><span>'+c+'</span>';it.onclick=function(){self.state.category=self.state.category===c?null:c;self.state.forecast=null;self.render();};list.appendChild(it);});box.appendChild(list);return box;};
Visual.prototype.monthExact=function(){var y=this.state.year,m=this.state.month;return this.events.filter(function(e){return e.type==='Data Exata'&&e.date&&e.date.getFullYear()===y&&e.date.getMonth()===m;});};
Visual.prototype.renderCalendar=function(){var self=this;var box=document.createElement('div');box.className='mcid-card mcid-calendar';var wh=document.createElement('div');wh.className='mcid-week-head';['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].forEach(function(w){var d=document.createElement('div');d.textContent=w;wh.appendChild(d);});box.appendChild(wh);var days=document.createElement('div');days.className='mcid-days';box.appendChild(days);var first=new Date(this.state.year,this.state.month,1);var start=new Date(this.state.year,this.state.month,1-first.getDay());var all=this.events.filter(function(e){return e.type==='Data Exata'&&e.date;});for(var i=0;i<42;i++){(function(){var d=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i);var k=keyDate(d);var evs=all.filter(function(e){return keyDate(e.date)===k;});var cell=document.createElement('div');cell.className='mcid-day'+(d.getMonth()!==self.state.month?' out':'')+(self.state.day&&sameDate(self.state.day,d)?' selected':'');cell.innerHTML='<div class="mcid-day-num">'+d.getDate()+'</div>';if(evs.length>=6){var total=document.createElement('div');total.className='mcid-total-label';total.textContent=evs.length+' eventos';cell.appendChild(total);var dots=document.createElement('div');dots.className='mcid-dots';CAT_ORDER.forEach(function(cat){var ce=evs.filter(function(e){return e.cat===cat;});if(!ce.length)return;var dot=document.createElement('span');dot.className='mcid-dot';dot.style.background=COLORS[cat];dot.title=cat+' — '+ce.length+' '+(ce.length===1?'evento':'eventos');dot.onmouseenter=function(evt){self.showTip(evt,cat,ce);};dot.onmousemove=function(evt){self.moveTip(evt);};dot.onmouseleave=function(){self.hideTip();};dot.onclick=function(evt){evt.stopPropagation();self.state.day=d;self.state.category=cat;self.state.forecast=null;self.render();};dots.appendChild(dot);});cell.appendChild(dots);}else if(evs.length){var by={};evs.forEach(function(e){(by[e.cat]=by[e.cat]||[]).push(e);});var bd=document.createElement('div');bd.className='mcid-badges';CAT_ORDER.forEach(function(cat){var ce=by[cat];if(!ce)return;var b=document.createElement('span');b.className='mcid-badge';b.style.background=COLORS[cat]+'18';b.style.borderColor=COLORS[cat]+'66';b.style.color=COLORS[cat];b.textContent=cat+(ce.length>1?' · '+ce.length:'');b.onmouseenter=function(evt){self.showTip(evt,cat,ce);};b.onmousemove=function(evt){self.moveTip(evt);};b.onmouseleave=function(){self.hideTip();};b.onclick=function(evt){evt.stopPropagation();self.state.day=d;self.state.category=cat;self.state.forecast=null;self.render();};bd.appendChild(b);});cell.appendChild(bd);}cell.onclick=function(){self.state.day=self.state.day&&sameDate(self.state.day,d)?null:d;self.state.forecast=null;if(!self.state.day)self.state.category=null;self.render();};days.appendChild(cell);})();}return box;};
Visual.prototype.showTip=function(evt,cat,evs){var t=this.tooltip;if(!t)return;var shown=evs.slice(0,3);var html='<strong>'+esc(cat)+' — '+evs.length+' '+(evs.length===1?'evento':'eventos')+'</strong>';shown.forEach(function(e){html+='<div class="tip-item">'+esc(e.project)+' — '+esc(e.city)+'/'+esc(e.uf)+'</div>';});if(evs.length>3)html+='<div class="tip-more">Ver mais</div>';t.innerHTML=html;t.style.display='block';this.moveTip(evt);};
Visual.prototype.moveTip=function(evt){if(!this.tooltip)return;var x=evt.clientX+14,y=evt.clientY+14;var maxX=window.innerWidth-350,maxY=window.innerHeight-170;this.tooltip.style.left=Math.max(8,Math.min(x,maxX))+'px';this.tooltip.style.top=Math.max(8,Math.min(y,maxY))+'px';};Visual.prototype.hideTip=function(){if(this.tooltip)this.tooltip.style.display='none';};
Visual.prototype.contextEvents=function(){var self=this;var evs=[];if(this.state.forecast){evs=this.forecastEvents(this.state.forecast);if(this.state.category)evs=evs.filter(function(e){return e.cat===self.state.category;});}else if(this.state.day){evs=this.events.filter(function(e){return e.type==='Data Exata'&&sameDate(e.date,self.state.day);});if(this.state.category)evs=evs.filter(function(e){return e.cat===self.state.category;});}else if(this.state.category){evs=this.monthExact().filter(function(e){return e.cat===self.state.category;});}else{var today=new Date(),y=this.state.year,m=this.state.month;var startDay=1;if(y===today.getFullYear()&&m===today.getMonth())startDay=today.getDate();evs=this.monthExact().filter(function(e){return e.date.getDate()>=startDay;});}evs.sort(function(a,b){var ad=a.date?a.date.getTime():0,bd=b.date?b.date.getTime():0;if(ad!==bd)return ad-bd;return String(a.tip).localeCompare(String(b.tip),'pt-BR');});return evs;};
Visual.prototype.contextTitle=function(evs){if(this.state.forecast==='q1')return (this.state.category?this.state.category.toUpperCase()+' • ':'')+'1ª QUINZENA • '+MONTHS[this.state.month].toUpperCase()+'/'+this.state.year;if(this.state.forecast==='q2')return (this.state.category?this.state.category.toUpperCase()+' • ':'')+'2ª QUINZENA • '+MONTHS[this.state.month].toUpperCase()+'/'+this.state.year;if(this.state.forecast==='nodate')return (this.state.category?this.state.category.toUpperCase()+' • ':'')+'SEM DATA';if(this.state.day&&this.state.category)return this.state.category.toUpperCase()+' • '+fmtDate(this.state.day);if(this.state.day)return 'EVENTOS DE '+fmtDate(this.state.day);if(this.state.category)return this.state.category.toUpperCase();return 'PRÓXIMOS EVENTOS';};
Visual.prototype.renderEvents=function(){var self=this;var evs=this.contextEvents();var box=document.createElement('div');box.className='mcid-card mcid-events';var head=document.createElement('div');head.className='mcid-events-head';head.innerHTML='<span class="mcid-small-cal"></span><div><div class="mcid-events-title">'+esc(this.contextTitle(evs))+'</div><div class="mcid-events-sub">'+evs.length+' '+(evs.length===1?'evento':'eventos')+' no contexto atual</div></div>';box.appendChild(head);var summary=document.createElement('div');summary.className='mcid-summary';var showSummary=!!(this.state.day||this.state.forecast);var summaryBase=evs;if(this.state.forecast)summaryBase=this.forecastEvents(this.state.forecast);else if(this.state.day)summaryBase=this.events.filter(function(e){return e.type==='Data Exata'&&sameDate(e.date,self.state.day);});if(showSummary){CAT_ORDER.forEach(function(cat){var n=summaryBase.filter(function(e){return e.cat===cat;}).length;if(!n)return;var b=document.createElement('button');b.className='mcid-summary-btn'+(self.state.category===cat?' active':'');b.innerHTML='<div class="mcid-summary-name" style="color:'+COLORS[cat]+'">'+cat+'</div><div class="mcid-summary-count">'+n+'</div>';b.onclick=function(){self.state.category=self.state.category===cat?null:cat;self.render();};summary.appendChild(b);});}box.appendChild(summary);var list=document.createElement('div');list.className='mcid-event-list';if(!evs.length){list.innerHTML='<div class="mcid-empty">Nenhum evento neste contexto.</div>';}else evs.forEach(function(e){var r=document.createElement('div');r.className='mcid-event-row';var chip=e.date?('<strong>'+String(e.date.getDate()).padStart(2,'0')+'</strong>'+MONTHS[e.date.getMonth()].slice(0,3).toUpperCase()):('<strong>—</strong>'+(e.type==='Quinzena'?(e.qn+'ª Q'):'SEM'));r.innerHTML='<div class="mcid-date-chip">'+chip+'</div><div><div class="mcid-event-line1"><span class="mcid-event-bullet" style="background:'+COLORS[e.cat]+'"></span>'+esc(e.tip)+'</div><div class="mcid-event-line2">'+esc(e.project)+'</div><div class="mcid-event-line3">'+esc(e.city)+' / '+esc(e.uf)+'</div></div>';r.title='Duplo clique: selecionar evento para navegação para Agenda de Eventos';r.onclick=function(){self.selectEvent(e,false);};r.ondblclick=function(evt){evt.preventDefault();self.selectEvent(e,true);};list.appendChild(r);});box.appendChild(list);return box;};
Visual.prototype.getFormattingModel=function(){
  var s=this.settings||{showTopBar:true,showFooter:true};
  return {cards:[{
    displayName:"Aparência",
    description:"Elementos visuais do Calendário Executivo MCid.",
    uid:"appearance-card",
    analyticsPane:false,
    groups:[{
      displayName:"Elementos",
      uid:"appearance-elements-group",
      slices:[
        {uid:"appearance-showTopBar",displayName:"Exibir barra institucional",control:{type:"ToggleSwitch",properties:{descriptor:{objectName:"appearance",propertyName:"showTopBar"},value:!!s.showTopBar}}},
        {uid:"appearance-showFooter",displayName:"Exibir rodapé",control:{type:"ToggleSwitch",properties:{descriptor:{objectName:"appearance",propertyName:"showFooter"},value:!!s.showFooter}}}
      ]
    }],
    revertToDefaultDescriptors:[
      {objectName:"appearance",propertyName:"showTopBar"},
      {objectName:"appearance",propertyName:"showFooter"}
    ]
  }]};
};
Visual.prototype.selectEvent=function(e,navigate){var self=this;if(e.selectionId&&this.selectionManager){try{this.selectionManager.select(e.selectionId,false);}catch(err){}}if(navigate){try{window.parent.postMessage({type:'MCID_CALENDAR_OPEN_EVENT',idEvento:e.id,selectionKey:e.selectionId&&e.selectionId.getKey?e.selectionId.getKey():null},'*');}catch(err2){}if(this.toast){this.toast.classList.add('show');setTimeout(function(){if(self.toast)self.toast.classList.remove('show');},1300);}}};

export default Visual;
